version: '3.8'

services:
  # Serviço do Redis
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_URI=redis://:123456@127.0.0.1:6379
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # Serviço do PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Serviço do seu backend
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: backend
#    environment:
#      - DB_DIALECT=postgres
#      - DB_HOST=db
#      - DB_PORT=5432
#      - DB_USER=user
#      - DB_PASS=senha
#      - DB_NAME=db_name
#      - REDIS_URI=redis://:123456@127.0.0.1:6379
#      - REDIS_OPT_LIMITER_MAX=1
#      - REDIS_OPT_LIMITER_DURATION=3000
#    ports:
#      - "4000:4000"
#    depends_on:
#      - redis
#      - db

volumes:
  redis-data:
  postgres-data:
